server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8
#canal配置
canal:
  host: 127.0.0.1
  port: 11111
  destination: example
  batchSize: 1000
  #配置规则，多个用逗号隔开
  filter: canal_example.user
#  filter: canal_example.*