server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8
#canal配置
canal:
  destination: example
  batchSize: 1000
  #配置规则，多个用逗号隔开
  filter: canal_example.user
  model: cluster
  cluster:
    zk-servers: 127.0.0.1:2181
    retry-times: 5
    retry-interval: 10000
  single:
    host: 127.0.0.1
    port: 11111